### ISSUE TITLE
Possible issue

### ISSUE THREAD

**Issue by JonathanKoh17** [goepigen/8.01SC-Classical-Mechanics#2]
For pset 1 question 2 either by integrating the velocity or simply taking the area under the graph, one would find that the displacement from 0 to 6T should be 5aT^2. By equating that to be h, shouldn't the answer thus be a=h/(5T^2)?

For pset 1 question 3 the acceleration of the stone is -g, not -gt.

**Comment by goepigen** [comment]
You are absolutely correct. In problem 2 there was an integration mistake, and in problem 3 it was a silly mistake that compounded into the final answer.

I have updated the calculations in both Problems 2 and 3. They are correct now. Thanks.

I have also added the Maple files I used to do that Problem set.
